on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]

name: Go
jobs:

  test:
    strategy:
      matrix:
        go-version: [1.13.x, 1.22.x, 1.23.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
        exclude:
            # There is no arm64 version of Go for darwin
          - go-version: "1.13.x"
            platform: "macos-latest"
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Ensure gofmt formatting
      if: matrix.platform == 'ubuntu-latest' && startsWith(matrix.go-version, '1.23')
      run: |
        [ "$(gofmt -l $(find . -name '*.go') 2>&1)" = "" ]

    - name: Download Go dependencies
      env:
        GOPROXY: "https://proxy.golang.org"
      run: go mod download

    - name: Test with -race
      run: go test -race -count=1 ./...

    - name: Integration test
      if: matrix.platform == 'ubuntu-latest' && startsWith(matrix.go-version, '1.23')
      run: go test -v -tags integration -exec=sudo -count=1 ./...

    - name: staticcheck.io
      if: matrix.platform == 'ubuntu-latest' && startsWith(matrix.go-version, '1.23')
      uses: dominikh/staticcheck-action@v1.3.1
      with:
        version: "2024.1.1"
        install-go: false
        cache-key: ${{ matrix.go }}
